QUESTIONS_DATA = [
    ("In which year did the Crimean War end?", "1856", ["1854", "1858", "1860"]),
    ("Who was the Tsar of Russia at the beginning of 1855?", "Nicholas I", ["Alexander I", "Alexander II", "Nicholas II"]),
    ("Which reform is associated with Alexander II in 1861?", "Emancipation of the serfs", ["Abolition of slavery", "Land redistribution", "Industrial revolution"]),
    ("What was the purpose of the Zemstva established in 1864?", "Local self-government", ["Military training", "Religious authority", "Foreign trade"]),
    ("Which military reform was implemented by Alexander II?", "Universal male conscription", ["Abolition of the military", "Professional soldiers only", "Voluntary enlistment"]),
    ("In what year was the Judicial Reform implemented?", "1864", ["1861", "1865", "1868"]),
    ("What was the Land and Liberty organization primarily focused on?", "Agrarian reform", ["Industrial development", "Naval expansion", "Religious reform"]),
    ("Who was assassinated in 1881?", "Alexander II", ["Alexander I", "Nicholas I", "Nicholas II"]),
    ("Which Tsar introduced the Fundamental Laws of 1906?", "Nicholas II", ["Alexander II", "Alexander III", "Nicholas I"]),
    ("What event triggered the 1905 Revolution?", "Bloody Sunday", ["Military defeat", "Famine", "Religious persecution"]),
    ("On which date did Bloody Sunday occur?", "22 January 1905", ["25 January 1905", "15 January 1905", "1 February 1905"]),
    ("Who led the peaceful march on Bloody Sunday?", "Father Gapon", ["Lenin", "Trotsky", "Martov"]),
    ("What were the Dumas established to function as?", "An advisory parliament", ["Executive committee", "Military council", "Religious court"]),
    ("How many Dumas were established before 1917?", "Four", ["Three", "Five", "Two"]),
    ("Which political party dominated the Third Duma?", "Octobrist Party", ["Socialist Party", "Liberal Party", "Conservative Party"]),
    ("What was the main cause of Russia's entry into World War I?", "Alliance with Serbia", ["Territorial ambitions", "Economic competition", "Ideological conflict"]),
    ("In which year did Russia enter World War I?", "1914", ["1913", "1915", "1916"]),
    ("What significant military defeat occurred in 1904-1905?", "Russo-Japanese War", ["Crimean War", "Russo-Turkish War", "World War I"]),
    ("Who led the Bolshevik faction of the RSDLP?", "Vladimir Lenin", ["Leon Trotsky", "Joseph Stalin", "Grigory Zinoviev"]),
    ("In which year did the first Russian Revolution occur?", "1917", ["1916", "1918", "1920"]),
    ("How many revolutions occurred in Russia in 1917?", "Two", ["One", "Three", "Four"]),
    ("Which month saw the February Revolution in 1917?", "March", ["February", "April", "May"]),
    ("What government was established after the February Revolution?", "Provisional Government", ["Soviet Government", "Duma Government", "Tsar's Council"]),
    ("Who was the prime minister of the Provisional Government?", "Alexander Kerensky", ["Pavel Milyukov", "Michael Rodzianko", "Alexei Krivoshein"]),
    ("In which month did the October Revolution occur?", "November", ["October", "September", "December"]),
    ("What was Lenin's most famous slogan during the October Revolution?", "Peace, Land, Bread", ["Workers of the world unite", "Death to the bourgeoisie", "Socialism or death"]),
    ("Which building was stormed during the October Revolution?", "Winter Palace", ["Summer Palace", "Kremlin", "Alexander Palace"]),
    ("What was the name of the first Soviet government?", "Council of People's Commissars", ["Soviet Executive", "Politburo", "Central Committee"]),
    ("In which year did the Russian Civil War begin?", "1918", ["1917", "1919", "1920"]),
    ("Who led the White Army during the Civil War?", "Anton Denikin", ["Lavr Kornilov", "Alexander Kolchak", "Nikolai Yudenich"]),
    ("What was War Communism?", "Emergency economic policy during Civil War", ["Peaceful coexistence policy", "Industrial development plan", "Agricultural reform"]),
    ("When did the Russian Civil War effectively end?", "1922", ["1920", "1921", "1923"]),
    ("What was the result of the Treaty of Brest-Litovsk?", "Russia withdrew from World War I", ["Russia gained territory", "Russia joined the Entente", "Russia invaded Poland"]),
    ("In which year was the Treaty of Brest-Litovsk signed?", "1918", ["1917", "1919", "1920"]),
    ("What new economic policy did Lenin introduce in 1921?", "New Economic Policy (NEP)", ["Planned economy", "Free market capitalism", "Agrarian collectivization"]),
    ("Which group led the Kronstadt Rebellion?", "Anarchists and Left SRs", ["White Army", "Mensheviks", "Liberals"]),
    ("In which year did the USSR form?", "1922", ["1921", "1923", "1924"]),
    ("Who became the leader of the Soviet Union after Lenin died in 1924?", "Joseph Stalin", ["Leon Trotsky", "Grigory Zinoviev", "Lev Kamenev"]),
    ("What was Stalin's policy of rapid industrialization called?", "Five-Year Plans", ["Great Leap Forward", "Cultural Revolution", "Four-Year Plans"]),
    ("In which year did the First Five-Year Plan begin?", "1928", ["1926", "1929", "1930"]),
    ("What was the name of Stalin's agricultural collectivization policy?", "Collectivization", ["Privatization", "Communalization", "Industrialization"]),
    ("Which group of peasants resisted collectivization?", "Kulaks", ["Muzhiks", "Mir leaders", "Landlords"]),
    ("How many people died during the Great Famine of 1932-1933?", "Between 5-10 million", ["1-2 million", "10-15 million", "20 million"]),
    ("What was the Great Purge also known as?", "The Great Terror", ["The Red Terror", "The White Terror", "The Dark Years"]),
    ("During which years did Stalin's Great Purge occur?", "1936-1938", ["1934-1936", "1935-1937", "1937-1939"]),
    ("Who were the main victims of the Great Purge?", "Old Bolsheviks and intellectuals", ["Kulaks", "Aristocrats", "Religious leaders"]),
    ("What were the show trials of 1936-1938 used to demonstrate?", "False confessions to treason", ["Justice of the system", "Guilt of the West", "Power of the people"]),
    ("In which year did Nazi Germany invade the Soviet Union?", "1941", ["1940", "1942", "1939"]),
    ("What was the German invasion of the Soviet Union called?", "Operation Barbarossa", ["Operation Typhoon", "Operation Blue", "Blitzkrieg"]),
    ("Which city was under siege for over 900 days during WWII?", "Leningrad", ["Moscow", "Stalingrad", "Kiev"]),
    ("What was the Soviet victory at this location in 1943 a turning point?", "Stalingrad", ["Kursk", "Berlin", "Moscow"]),
    ("How many Soviet citizens died during World War II?", "Approximately 27 million", ["10 million", "15 million", "35 million"]),
    ("Who was Stalin's main ally during World War II?", "Britain and America", ["Japan", "Italy", "Germany"]),
    ("In which year did World War II end for the Soviet Union?", "1945", ["1944", "1946", "1943"]),
    ("What term describes the conflict between the USSR and USA after WWII?", "Cold War", ["Warm War", "Proxy War", "Ideological War"]),
    ("When did the Cold War officially begin?", "1947", ["1945", "1946", "1948"]),
    ("What was the Cominform established for?", "Communist international organization", ["Soviet intelligence", "Military alliance", "Economic cooperation"]),
    ("Which European countries fell under Soviet control after WWII?", "Poland, Hungary, Czechoslovakia, East Germany", ["France, Italy, Belgium", "Spain, Portugal, Greece", "Balkans, Turkey, Greece"]),
    ("What was the Iron Curtain?", "Barrier between Eastern and Western Europe", ["Soviet propaganda", "Military defense line", "Economic boundary"]),
    ("In which year did Stalin die?", "1953", ["1951", "1954", "1952"]),
    ("Who succeeded Stalin as leader of the Soviet Union?", "Nikita Khrushchev", ["Georgy Malenkov", "Lavrenty Beria", "Vyacheslav Molotov"]),
    ("What was Khrushchev's policy called that allowed criticism of Stalin?", "De-Stalinization", ["Liberalization", "Reformation", "Thawing"]),
    ("In which year did Khrushchev deliver his secret speech criticizing Stalin?", "1956", ["1954", "1957", "1955"]),
    ("Which Hungarian city saw a major uprising in 1956?", "Budapest", ["Prague", "Warsaw", "Berlin"]),
    ("How did the Soviet Union respond to the Hungarian Uprising?", "Military invasion", ["Negotiation", "Economic sanctions", "Diplomatic pressure"]),
    ("What was the Cuban Missile Crisis?", "Soviet nuclear missiles in Cuba", ["American invasion of Cuba", "Soviet occupation of Cuba", "American blockade of Russia"]),
    ("In which year did the Cuban Missile Crisis occur?", "1962", ["1961", "1963", "1960"]),
    ("What was the Space Race?", "Competition to reach space", ["Competition for oil", "Military arms race", "Economic competition"]),
    ("Who became leader of the Soviet Union after Khrushchev?", "Leonid Brezhnev", ["Nikolai Podgorny", "Alexei Kosygin", "Mikhail Suslov"]),
    ("What period of Soviet history is known as the 'Era of Stagnation'?", "Brezhnev era 1964-1982", ["Stalin era", "Khrushchev era", "Post-Soviet era"]),
    ("What was the Brezhnev Doctrine?", "Soviet intervention in allied states", ["Nuclear deterrence", "Economic cooperation", "Cultural exchange"]),
    ("Which country did the Soviet Union invade in 1968?", "Czechoslovakia", ["Poland", "Hungary", "East Germany"]),
    ("What was the Prague Spring?", "Czechoslovak reform movement", ["Soviet policy", "Polish revolution", "American intervention"]),
    ("In which year did the Soviet Union invade Afghanistan?", "1979", ["1978", "1980", "1981"]),
    ("Why did the Soviet Union invade Afghanistan?", "To support communist government", ["To access oil", "To invade Pakistan", "To stop NATO"]),
    ("What were the gulags?", "Soviet labor camps", ["Government offices", "Military bases", "Prisons"]),
    ("How many people died in the gulags?", "Millions", ["Thousands", "Hundreds of thousands", "Billions"]),
    ("What was the purpose of the KGB?", "Secret police and intelligence", ["Military command", "Government administration", "Economic planning"]),
    ("Who was the founder of the Soviet Union?", "Vladimir Lenin", ["Joseph Stalin", "Leon Trotsky", "Grigory Zinoviev"]),
    ("What was the main ideology of the Soviet Union?", "Communism", ["Fascism", "Capitalism", "Socialism"]),
    ("Which class was supposed to lead the communist revolution according to Marx?", "Working class", ["Peasants", "Intellectuals", "Soldiers"]),
    ("What was the name of the secret police under Lenin?", "Cheka", ["NKVD", "Gestapo", "KGB"]),
    ("Who was exiled from the Soviet Union in 1929?", "Leon Trotsky", ["Grigory Zinoviev", "Lev Kamenev", "Nikolai Bukharin"]),
    ("What was the doctrine of 'Socialism in One Country'?", "Stalin's policy", ["Trotsky's policy", "Lenin's policy", "Khrushchev's policy"]),
    ("How many years of the 20th century did the Soviet Union exist?", "69 years (1922-1991)", ["70 years", "75 years", "65 years"]),
    ("What was the Union Treaty that formed the USSR called?", "Treaty of Union", ["Treaty of Russia", "Treaty of Moscow", "Treaty of Socialist States"]),
    ("Which republics initially formed the Soviet Union in 1922?", "RSFSR, Ukrainian SSR, Byelorussian SSR, Transcaucasian SFSR", ["Just RSFSR", "15 republics", "10 republics"]),
    ("What was the purpose of the Comintern?", "International communist organization", ["Soviet military", "Soviet economy", "Soviet culture"]),
    ("In which year was the Comintern dissolved?", "1943", ["1941", "1945", "1940"]),
    ("What was the Red Army?", "Soviet military force", ["Communist political party", "Revolutionary movement", "Secret police"]),
    ("Who was the first commander of the Red Army?", "Leon Trotsky", ["Mikhail Tukhachevsky", "Grigory Zinoviev", "Sergei Budyonny"]),
    ("What was the Great Patriotic War?", "Soviet name for World War II", ["Civil War name", "Russian-Japanese War name", "Cold War name"]),
    ("How many soldiers did the Soviet Union deploy in WWII?", "Over 30 million", ["10 million", "15 million", "25 million"]),
    ("What was the Eastern Front in WWII?", "German-Soviet theater of war", ["German-British theater", "American-Soviet theater", "Italian theater"]),
    ("Which Soviet general is famous for the defense of Stalingrad?", "Georgy Zhukov", ["Konstantin Rokossovsky", "Alexander Vasilevsky", "Aleksandr Suvorov"]),
    ("What was the significance of the Battle of Kursk in 1943?", "Largest tank battle", ["First Soviet victory", "End of war", "German breakthrough"]),
    ("In which year did Soviet forces enter Berlin?", "1945", ["1944", "1946", "1943"]),
    ("Who liberated the concentration camps in Eastern Europe?", "Soviet forces", ["American forces", "British forces", "Polish forces"]),
    ("What was the Warsaw Uprising?", "Polish resistance against Nazi occupation", ["Soviet revolution", "Communist movement", "German attack"]),
    ("What was the significance of Yalta Conference?", "Allied war leaders met", ["Treaty signed", "War ended", "Germany defeated"]),
    ("What was the significance of the Potsdam Conference?", "Post-war settlement discussions", ["War declaration", "Peace treaty", "Alliance formation"]),
    ("Which Soviet leader attended the Yalta Conference?", "Joseph Stalin", ["Nikita Khrushchev", "Leonid Brezhnev", "Mikhail Gorbachev"]),
    ("What was the Molotov-Ribbentrop Pact?", "Nazi-Soviet Non-Aggression Pact 1939", ["Post-war treaty", "Economic agreement", "Military alliance"]),
    ("In which year was the Molotov-Ribbentrop Pact signed?", "1939", ["1938", "1940", "1941"]),
    ("What did the Molotov-Ribbentrop Pact include?", "Secret protocols dividing Eastern Europe", ["Trade agreement", "Military cooperation", "Cultural exchange"]),
    ("Who was Vyacheslav Molotov?", "Soviet foreign minister", ["Soviet military leader", "Soviet propaganda chief", "Soviet economist"]),
    ("What was the Molotov Plan?", "Soviet economic cooperation in Eastern Europe", ["American aid program", "German economic plan", "Japanese investment"]),
    ("What was the Berlin Blockade?", "Soviet attempt to starve West Berlin", ["American military action", "German occupation", "Allied assault"]),
    ("In which year did the Berlin Blockade occur?", "1948-1949", ["1947-1948", "1949-1950", "1946-1947"]),
    ("How did the Allies respond to the Berlin Blockade?", "Berlin Airlift", ["Military invasion", "Economic sanctions", "Diplomatic negotiations"]),
    ("What was the NATO alliance?", "Western military alliance against USSR", ["Soviet alliance", "Economic union", "Cultural organization"]),
    ("In which year was NATO founded?", "1949", ["1948", "1950", "1947"]),
    ("What was the Warsaw Pact?", "Soviet military alliance in Eastern Europe", ["Soviet economic union", "Soviet political party", "Soviet trade organization"]),
    ("In which year was the Warsaw Pact established?", "1955", ["1954", "1956", "1957"]),
    ("What was the Hungarian Revolution of 1956?", "Uprising against Soviet domination", ["Communist revolution", "German invasion", "American intervention"]),
    ("Who was Imre Nagy?", "Hungarian Prime Minister during 1956 Uprising", ["Soviet general", "American ambassador", "Polish leader"]),
    ("What happened to Imre Nagy?", "He was executed", ["He escaped to the West", "He became president", "He was exiled"]),
    ("What was the Prague Spring of 1968?", "Czech reform movement", ["Soviet military exercise", "American intervention", "German expansion"]),
    ("Who was Alexander Dubcek?", "Czechoslovak leader during Prague Spring", ["Soviet general", "Hungarian revolutionary", "Polish activist"]),
    ("What was the purpose of Soviet intervention in Prague?", "Stop reform movement", ["Support reforms", "Install new leader", "Economic aid"]),
    ("What was the Soviet intervention in Afghanistan called?", "Soviet-Afghan War", ["Operation Cyclone", "Desert Storm", "Cold War campaign"]),
    ("Who supported the Afghan Mujahideen against the Soviets?", "United States and Pakistan", ["Britain and France", "China alone", "Iran and Syria"]),
    ("How long did the Soviet occupation of Afghanistan last?", "1979-1989", ["1980-1988", "1978-1988", "1981-1990"]),
    ("How many Soviet soldiers died in Afghanistan?", "Over 14,000", ["5,000", "10,000", "20,000"]),
    ("What was the impact of Afghanistan on the Soviet Union?", "Economic and military strain", ["Economic benefit", "Military strength", "Political unity"]),
    ("What was glasnost?", "Gorbachev's policy of openness", ["Economic reform", "Military expansion", "Cultural control"]),
    ("What was perestroika?", "Gorbachev's restructuring policy", ["Communist ideology", "Military strategy", "Agricultural reform"]),
    ("In which year did Mikhail Gorbachev become Soviet leader?", "1985", ["1984", "1986", "1983"]),
    ("What were the consequences of glasnost and perestroika?", "Collapse of Soviet Union", ["Strengthened USSR", "Economic growth", "Communist revival"]),
    ("In which year did the Soviet Union officially dissolve?", "1991", ["1990", "1992", "1989"]),
    ("Which event symbolized the end of the Cold War?", "Fall of Berlin Wall in 1989", ["Gulf War", "End of USSR", "Korean War end"]),
    ("What was the significance of the Chernobyl disaster?", "Nuclear accident showing system flaws", ["Military victory", "Scientific achievement", "Economic success"]),
    ("In which year did the Chernobyl disaster occur?", "1986", ["1985", "1987", "1988"])
]
